name: tropical-wood
version: v1

services:
- name: backend
  source_dir: backend
  github:
    branch: main
    repo: appfrabric/roilux
  run_command: uvicorn main:app --host 0.0.0.0 --port 8000
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8000
  routes:
  - path: /api
  envs:
  - key: ENV
    value: production
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: HOST
    value: "0.0.0.0"
  - key: PORT
    value: "8000"

- name: frontend
  source_dir: frontend
  github:
    branch: main 
    repo: appfrabric/roilux
  build_command: npm ci && npm run build
  run_command: npx serve -s build -l 3000
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: GENERATE_SOURCEMAP
    value: "false"