version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: roilux-backend
    expose:
      - "8000"
    volumes:
      - uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - roilux-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: roilux-frontend
    ports:
      - "80:80"
      - "443:443"  # For HTTPS in production
    depends_on:
      - backend
    networks:
      - roilux-network
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  roilux-network:
    driver: bridge

volumes:
  uploads:
    driver: local