name: tropical-wood
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: appfrabric/roilux
  name: frontend
  run_command: npx serve -c serve.json -p $PORT
  source_dir: frontend
  build_command: npm install && npm run build
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: GENERATE_SOURCEMAP
    value: "false"

- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: appfrabric/roilux
  name: backend
  run_command: uvicorn main:app --host 0.0.0.0 --port $PORT
  source_dir: backend
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  envs:
  - key: ENV
    value: production
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: HOST
    value: 0.0.0.0
  - key: DATABASE_URL
    value: sqlite:///./data/tropical_wood.db