# DigitalOcean App Platform Configuration for Tropical Wood
# This file tells DigitalOcean exactly how to build and deploy your app

name: tropical-wood
region: nyc

services:
  # Frontend React Application
  - name: frontend
    source_dir: /frontend
    github:
      repo: appfrabric/roilux
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    http_port: 80
    run_command: npx serve -s build -l 80
    envs:
      - key: NODE_ENV
        value: production
      - key: GENERATE_SOURCEMAP
        value: "false"
      - key: REACT_APP_API_URL
        value: ${backend.PUBLIC_URL}

  # Backend FastAPI Application  
  - name: backend
    source_dir: /backend
    github:
      repo: appfrabric/roilux
      branch: main
      deploy_on_push: true
    build_command: pip install -r requirements.txt
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8000
    run_command: uvicorn main:app --host 0.0.0.0 --port 8000
    routes:
      - path: /api
        preserve_path_prefix: false
    envs:
      - key: FRONTEND_URL
        value: ${frontend.PUBLIC_URL}
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "8000"

# Health checks
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

# Database (optional - for future use)
# databases:
#   - name: tropical-wood-db
#     engine: PG
#     version: "13"
#     size: basic-xs