name: tropical-wood
services:
- dockerfile_path: Dockerfile.app
  github:
    branch: main
    deploy_on_push: true
    repo: appfrabric/roilux
  name: app
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: DATABASE_URL
    value: sqlite:///./data/tropical_wood.db