name: tropical-wood
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: appfrabric/roilux
  name: frontend
  run_command: npm start
  source_dir: frontend
  build_command: npm ci --legacy-peer-deps && NODE_ENV=production npm run build && echo "Build complete, server.js exists:" && ls -la server.js
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: GENERATE_SOURCEMAP
    value: "false"
  - key: CI
    value: "true"
  - key: BACKEND_URL
    value: "http://backend:8080"

- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: appfrabric/roilux
  name: backend
  build_command: pip install -r requirements.txt
  run_command: python -m uvicorn main:app --host 0.0.0.0 --port 8080
  source_dir: backend
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: ENV
    value: production
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: DATABASE_URL
    value: sqlite:///./data/tropical_wood.db