name: Deploy to DigitalOcean App Platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test backend
      working-directory: ./backend
      run: |
        # Run basic health check test
        python -c "from main import app; from fastapi.testclient import TestClient; client = TestClient(app); response = client.get('/health'); assert response.status_code == 200"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to DigitalOcean App Platform
      uses: digitalocean/app_action@v1.1.5
      with:
        app_name: tropical-wood
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        
    - name: Notify deployment
      if: success()
      run: |
        echo "🌴 Tropical Wood deployed successfully to DigitalOcean App Platform!"
        echo "Frontend: Available at your app URL"
        echo "Backend API: Available at your app URL/api"